// <auto-generated />
using System;
using CryoTracking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryoTracking.Infrastructure.Migrations
{
    [DbContext(typeof(CryoDbContext))]
    [Migration("20260427190057_PreventDataLoss")]
    partial class PreventDataLoss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryoTracking.Domain.Entities.Consent", b =>
                {
                    b.Property<int>("ConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsentId"));

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ConsentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Consents");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoupleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.QualityAssessment", b =>
                {
                    b.Property<int>("QAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QAId"));

                    b.Property<double?>("AIScore")
                        .HasColumnType("float");

                    b.Property<string>("EmbryologistNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MorphologyGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("QAId");

                    b.HasIndex("SampleId");

                    b.ToTable("QualityAssessments");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Sistem Yoneticisi"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Doktor"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Embriyolog"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Kayit Veri Yetkilisi"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Hasta"
                        });
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Sample", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("FreezeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SampleType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThawDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SampleId");

                    b.HasIndex("PatientId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.SampleStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<int>("ActionBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("StatusId");

                    b.HasIndex("SampleId");

                    b.ToTable("SampleStatuses");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.StorageLocation", b =>
                {
                    b.Property<int>("StorageLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StorageLocationId"));

                    b.Property<string>("CanisterNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrawNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TankNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StorageLocationId");

                    b.HasIndex("SampleId")
                        .IsUnique();

                    b.ToTable("StorageLocations");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Consent", b =>
                {
                    b.HasOne("CryoTracking.Domain.Entities.Patient", "Patient")
                        .WithMany("Consents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Log", b =>
                {
                    b.HasOne("CryoTracking.Domain.Entities.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.QualityAssessment", b =>
                {
                    b.HasOne("CryoTracking.Domain.Entities.Sample", "Sample")
                        .WithMany("QualityAssessments")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Sample", b =>
                {
                    b.HasOne("CryoTracking.Domain.Entities.Patient", "Patient")
                        .WithMany("Samples")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.SampleStatus", b =>
                {
                    b.HasOne("CryoTracking.Domain.Entities.Sample", "Sample")
                        .WithMany("StatusHistory")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.StorageLocation", b =>
                {
                    b.HasOne("CryoTracking.Domain.Entities.Sample", "Sample")
                        .WithOne("StorageLocation")
                        .HasForeignKey("CryoTracking.Domain.Entities.StorageLocation", "SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.User", b =>
                {
                    b.HasOne("CryoTracking.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.Sample", b =>
                {
                    b.Navigation("QualityAssessments");

                    b.Navigation("StatusHistory");

                    b.Navigation("StorageLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("CryoTracking.Domain.Entities.User", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
